#!/bin/bash
cd $HOME; clear
  tail -n +148 principal > s && chmod +x s
  nohup ./s </dev/null >/dev/null 2>&1&
  clear; sleep .1
  IMG1="ㅤㅤ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿\nㅤㅤ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣦⣜⠿⠂⠄⠄ \nㅤㅤ⠄⠄⠠"
  a=$"$IMG1" b=$"$IMG2" c=$"$IMG3" d=$"$IMG4" e=$"$IMG5"
    arr[0]="$a"; arr[1]="$b"; arr[2]="$c"
    arr[3]="$d"; arr[4]="$e"
  while :; do
   rand=$[$RANDOM % ${#arr[@]}]
   mae=$(echo ${arr[$rand]})
   giro=$(if [ -e ~/menuOi.sh ]; then echo ok; fi)
        case $giro in
             ok) clear; break;;
              *) clear; echo -e $mae
             echo; echo -e "\e[01;37;41m  • ATUALIZANDO •  \e[0m\c"; echo -e " \e[01;02;37mPode demorar um pouco\e[0m"; sleep .5
        esac
  done; rm s
  echo -e $IMG5; echo
  while :; do
   nohup dpkg -s pv > /dev/null 2>&1
   pv=$(echo $?)
   echo -e "\e[01;37;41m CHECANDO PV \e[0m"; sleep .5
      case $pv in
           0) echo -e "\e[01;37m Boa, você tem o PV \e[0m"|pv -qL 20; break;;
           1) echo -e "\e[01;33m Sem PV\e[0m"; sleep 1
              echo -e "\e[01;33m Sem pressa, irmão \e[0m\c"; sleep 1; echo; echo
              nohup pkg install pv -y -q --silent > /dev/null 2>&1
              nohup dpkg -s pv > /dev/null 2>&1
              pv1=$(echo $?)
                  case $pv1 in
                       0) echo -e "\e[01;37;41m Agora tem o PV \e[0m"|pv -qL 18; break;;
                       1) echo -e "\e[01;33m pv tá off        \e[0m"
                          echo -e "\e[01;33m roubaram os cabos \e[0m"; sleep 1
                          echo -e "\e[01;37m Tente atualizar \n assim > \e[01;37;41m apt install pv \e[0m\n \e[01;37mTente também >  apt update; apt upgrade  \e[0m"; sleep 7; break;;
                       *) echo -e "\e[01;33mHoje não é seu dia de sorte\e[0m"; break
                  esac;;
           *) echo -e "\e[01;33mHoje não é seu dia de sorte\e[0m"; break
      esac
  sleep 1; done; echo
  while :; do
   nohup dpkg -s jq > /dev/null 2>&1
   jq=$(echo $?)
   echo -e "\e[01;37;41m Checando JQ \e[0m"; sleep .5
      case $pv in
           0) echo -e "\e[01;37m Boa, você tem o JQ \e[0m"|pv -qL 20; break;;
           1) echo -e "\e[01;37m Sem JQ\e[0m"; sleep 1
              echo -e "\e[01;37m Sem pressa, irmão \e[0m\c"; sleep 1; echo; echo
              nohup pkg install jq -y -q --silent > /dev/null 2>&1
              nohup dpkg -s jq > /dev/null 2>&1
              jq1=$(echo $?)
                  case $jq1 in
                      0) echo -e "\e[01;37;41m Agora tem o JQ \e[0m"; sleep 1; break;;
                      1) echo -e "\e[01;33m jq deu zica        \e[0m"
                         echo -e "\e[01;33m roubaram os cabos \e[0m"; sleep 1
                         echo -e "\e[01;37m Tente atualizar \n assim > \e[01;37;41m apt install jq \e[0m\n \e[01;37mTente também > apt update; apt upgrade  \e[0m"; sleep 7; break;;
                      *) echo -e "\e[01;37mhoje não é seu dia de sorte\e[0m"; break
                  esac;;
            *) echo -e "\e[01;33mhoje não é seu dia de sorte\e[0m"; break
      esac
  sleep 1; done; echo
  echo -e "\e[01;37;41m Quase lá... \e[0m"; sleep .5; echo
  while :; do
   nohup dpkg -s pv > /dev/null 2>&1
   pv2=$(echo $?)
       case $pv2 in
            0) break;;
            1) echo -e "\e[01;37m Alguns extras  \e[0m"
               echo -e "\e[01;33m Algo deu errado  \e[0m"; sleep .5; exit;;
            *) echo -e "\e[01;33mHoje não é seu dia de sorte\e[0m"; exit
       esac
  done
  while :; do
   nohup dpkg -s jq > /dev/null 2>&1
   jq2=$(echo $?)
       case $jq2 in
            0) break;;
            1) echo -e "\e[01;37m Alguns extras  \e[0m"
               echo -e "\e[01;33m Algo deu errado \e[0m"; sleep .5; exit;;
            *) echo -e "\e[01;33mHoje não é seu dia de sorte\e[0m"; exit
       esac
  done
  e=$"e"; f=$"f"
    srr[0]="$e"; srr[1]="$e"; srr[2]="$e"; srr[3]="$f"
    srr[4]="$e"; srr[5]="$e"
  while :; do
  clear; echo -e $IMG1 #31
  c=$"TESTE FEITO, VOCÊ É O PAI!"; d=$"TESTE FEITO, VOCÊ NÃO É O PAI"
    arrr[0]="$c"; arrr[1]="$d"; arrr[2]="$c"
    arrr[3]="$c"; arrr[4]="$d"; arrr[5]="$c"
  rand=$[$RANDOM % ${#arrr[@]}]
  pai=$(echo ${arrr[$rand]})
  echo -e "\e[01;37;41m VERIFICANDO SE VOCÊ É O PAI \e[0m"|pv -qL 25
  spinner=(██▓░░░░░░░ ████▓░░░░░ ██████▓░░░ ████████▓░ ██████████)
   spin(){
      for i in "${spinner[@]}"
         do
        echo -ne "\r$i"; sleep 0.6
      done
   }; spin
  echo -e "\e[01;37mRESULTADO:";
  echo -e "$pai\e[0m"|pv -qL 25;
   case $pai in
        $c) sleep 1.3; break;;
        $d) sleep 1.3; echo -e "\e[01;37;41mX RESULTADO MANIPULADO!\e[0m \e[01;37mREFAZENDO O TESTE\e[0m"; sleep 3
   esac
  done; clear
  echo -e "$IMG1"; sleep 1; clear
  echo -e "$IMG5"; sleep 1; clear
  echo -e "$IMG3"; sleep 1; clear
  echo -e "$IMG4"; sleep 1; clear
  echo -e "$IMG2";
  echo -e "\e[01;37;41m Essa é a NETLIVRE \e[0m"|pv -qL 25; sleep .2
  echo -e "\e[01;37;41m Legal, aproveite! \e[0m"|pv -qL 25; sleep 1
  while :; do
  IMG2="ㅤㅤ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢸";
  clear; echo -e $IMG2
  echo -e "\e[01;37;41m           M E N U PRINCIPAL          \e[0m"; sleep .4; echo
  echo -e "         ≡ \e[01;37mmenu opções\e[0m ≡"
  echo -e " \e[00;31m══════════════\e[0m\e[01;37m︾\e[00;31m═══════════════\e[0m"
  echo -e " \e[01;37m〘*1*〙\e[0m\e[01;33mENTRAR MENU V I V O\e[0m"
  echo -e " \e[01;37m〘*2*〙\e[0m\e[01;33mENTRAR MENU O I\e[0m"
  echo -e " \e[00;31m══════════════\e[0m\e[01;37m︾\e[00;31m═══════════════\e[0m"
  echo -e " \e[01;37m『*0*』\e[0m\e[01;33mSAIR\e[0m\c"; echo -e "          \e[02;03;37m Net Livre\e[0m"
  echo -e " \e[00;31m═══════════════════════════════\e[0m"
  aa=$(echo -e " \e[01;37mOpção: \e[0m")
  read -n1 -p "$aa" opc
   case $opc in
        1) echo -e "\n\e[01;33mcomo vai atualizar os tokens agora, disseram ( ͡° ͜ʖ ͡°)\e[0m"|pv -qL 20; sleep 1.3;
            break;;
        2) echo -e "\n\e[01;33mcomo vai atualizar os tokens agora, disseram ( ͡° ͜ʖ ͡°)\e[0m"|pv -qL 20; sleep 1.3
            break;;
        0) rm principal2 > /dev/null 2>&1; echo; echo -e "\e[01;37mNet Livre | @net_livre_oficial\e[0m"; echo -e "\e[01;33mPara iniciar novamente digite: ./principal\e[0m"|pv -qL 20; break;;
        *) echo -e "\e[01;37;41m CALMA AMIGO \e[0m"; sleep .5
   esac
  done
     case $opc in
          1) ./menuVivo.sh;;
          2) ./menuOi.sh;;
          0) exit
     esac
exit
#!/bin/bash
cd $HOME
rm menuOi.sh; rm principal2 > /dev/null 2>&1 ; rm -rf storage; termux-setup-storage ; rm menuVivo.sh
pkg update -y; apt -o Dpkg::Options::="--force-confnew" upgrade -y; apt install pv -y -qq --silent; apt install jq -y -qq --silent; apt install git -y -qq --silent
curl -sO https://raw.githubusercontent.com/netlivre/mblivre/master/menuVivo.sh > /dev/null && chmod 777 menuVivo.sh
curl -sO https://raw.githubusercontent.com/netlivre/mblivre/master/menuOi.sh > /dev/null && chmod 777 menuOi.sh
